export const STATES = [
  { id: 'state_andhra_pradesh', name: 'Andhra Pradesh' },
  { id: 'state_arunachal_pradesh', name: 'Arunachal Pradesh' },
  { id: 'state_assam', name: 'Assam' },
  { id: 'state_bihar', name: 'Bihar' },
  { id: 'state_chhattisgarh', name: 'Chhattisgarh' },
  { id: 'state_goa', name: 'Goa' },
  { id: 'state_gujarat', name: 'Gujarat' },
  { id: 'state_haryana', name: 'Haryana' },
  { id: 'state_himachal_pradesh', name: 'Himachal Pradesh' },
  { id: 'state_jharkhand', name: 'Jharkhand' },
  { id: 'state_karnataka', name: 'Karnataka' },
  { id: 'state_kerala', name: 'Kerala' },
  { id: 'state_madhya_pradesh', name: 'Madhya Pradesh' },
  { id: 'state_maharashtra', name: 'Maharashtra' },
  { id: 'state_manipur', name: 'Manipur' },
  { id: 'state_meghalaya', name: 'Meghalaya' },
  { id: 'state_mizoram', name: 'Mizoram' },
  { id: 'state_nagaland', name: 'Nagaland' },
  { id: 'state_odisha', name: 'Odisha' },
  { id: 'state_punjab', name: 'Punjab' },
  { id: 'state_rajasthan', name: 'Rajasthan' },
  { id: 'state_sikkim', name: 'Sikkim' },
  { id: 'state_tamil_nadu', name: 'Tamil Nadu' },
  { id: 'state_telangana', name: 'Telangana' },
  { id: 'state_tripura', name: 'Tripura' },
  { id: 'state_uttar_pradesh', name: 'Uttar Pradesh' },
  { id: 'state_uttarakhand', name: 'Uttarakhand' },
  { id: 'state_west_bengal', name: 'West Bengal' },
  { id: 'state_andaman_nicobar', name: 'Andaman & Nicobar' },
  { id: 'state_chandigarh', name: 'Chandigarh' },
  { id: 'state_dadra_nagar_haveli', name: 'Dadra & Nagar Haveli' },
  { id: 'state_daman_diu', name: 'Daman & Diu' },
  { id: 'state_delhi', name: 'Delhi' },
  { id: 'state_jammu_kashmir', name: 'Jammu & Kashmir' },
  { id: 'state_ladakh', name: 'Ladakh' },
  { id: 'state_lakshadweep', name: 'Lakshadweep' },
  { id: 'state_puducherry', name: 'Puducherry' },
]
